const PDFDocument = require('pdfkit');

function generatePrescriptionPDF(prescription, patient, doctor) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const chunks = [];

      doc.on('data', chunk => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // --- Diagonal Watermark ---
      doc.save();
      doc.fontSize(60);
      doc.fillColor('#e0f2fe');
      doc.opacity(0.15);
      doc.rotate(-45, { origin: [300, 400] });
      doc.text('VIRTUALCARE NIGERIA', 50, 350, { width: 700 });
      doc.restore();

      // --- Header ---
      doc.rect(0, 0, doc.page.width, 100).fill('#0066cc');
      doc.fontSize(24).fillColor('#ffffff').text('Virtualcare Nigeria', 50, 30);
      doc.fontSize(10).fillColor('#bfdbfe').text('MDCN-Compliant Telemedicine Platform', 50, 60);
      doc.fontSize(10).text('www.virtualcare.me | support@virtualcare.me', 50, 75);

      // --- Prescription Title ---
      doc.moveDown(3);
      doc.fontSize(18).fillColor('#1e293b').text('Medical Prescription', { align: 'center' });
      doc.moveDown(0.5);
      const rxDate = prescription.createdAt || prescription.issuedAt || new Date();
      doc.fontSize(10).fillColor('#64748b').text(`Date: ${new Date(rxDate).toLocaleDateString('en-NG', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}`, { align: 'center' });

      // --- Patient Info ---
      doc.moveDown(1.5);
      doc.rect(50, doc.y, doc.page.width - 100, 60).fill('#f0f9ff').stroke('#bae6fd');
      const patientY = doc.y + 10;
      doc.fontSize(11).fillColor('#0c4a6e').text(`Patient: ${patient.name} ${patient.surname}`, 60, patientY);
      doc.text(`Email: ${patient.email}`, 60, patientY + 16);
      doc.text(`Phone: ${patient.phone || 'N/A'}`, 60, patientY + 32);

      // --- Doctor Info ---
      doc.moveDown(3);
      doc.rect(50, doc.y, doc.page.width - 100, 45).fill('#f0fdf4').stroke('#bbf7d0');
      const docY = doc.y + 10;
      doc.fontSize(11).fillColor('#166534').text(`Prescribing Doctor: Dr. ${doctor.name} ${doctor.surname}`, 60, docY);
      doc.text(`Specialty: ${doctor.specialty || 'General Practice'} | MDCN Verified`, 60, docY + 16);

      // --- Medications ---
      doc.moveDown(3);
      doc.fontSize(14).fillColor('#1e293b').text('Medications', 50);
      doc.moveDown(0.5);

      const medications = prescription.medications || [];
      medications.forEach((med, i) => {
        doc.moveDown(0.3);
        doc.fontSize(12).fillColor('#0066cc').text(`${i + 1}. ${med.name}`, 60);
        doc.fontSize(10).fillColor('#475569').text(`   Dosage: ${med.dosage || 'As directed'}`, 70);
        if (med.frequency) doc.text(`   Frequency: ${med.frequency}`, 70);
        if (med.duration) doc.text(`   Duration: ${med.duration}`, 70);
        if (med.notes) doc.text(`   Notes: ${med.notes}`, 70);
      });

      // --- Notes ---
      if (prescription.notes) {
        doc.moveDown(1.5);
        doc.fontSize(12).fillColor('#1e293b').text('Additional Notes', 50);
        doc.moveDown(0.3);
        doc.fontSize(10).fillColor('#475569').text(prescription.notes, 60, doc.y, { width: doc.page.width - 120 });
      }

      // --- Footer ---
      const footerY = doc.page.height - 60;
      doc.rect(0, footerY, doc.page.width, 60).fill('#f8fafc');
      doc.fontSize(8).fillColor('#94a3b8')
        .text('Generated by Virtualcare Nigeria — virtualcare.me', 50, footerY + 15, { align: 'center', width: doc.page.width - 100 })
        .text(`© ${new Date().getFullYear()} Virtualcare Nigeria. This prescription is digitally generated and valid.`, 50, footerY + 28, { align: 'center', width: doc.page.width - 100 });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

module.exports = { generatePrescriptionPDF };
